CALCULATOR_SCRIPT=main.py

all:
	pip install -r requirements.txt
	@echo "🚀 Starte das Scraping des ECTS-Notenblatts aus dem Prüfungsportal und berechne den Notendurchschnitt.."
	python $(CALCULATOR_SCRIPT)

calculate:
	@echo "🚀 Starte das Scraping des ECTS-Notenblatts aus dem Prüfungsportal und berechne den Notendurchschnitt.."
	python $(CALCULATOR_SCRIPT)